version: "3"
services:
  scm-backup:
    image: drewmoseley/scm-backup:latest
    container_name: scm-backup
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${PWD}/settings.yml:/opt/scm-backup/settings.yml
      - /backup/scm-backup/:/scm-backup/
